<?php
define('ROOT_NAME', 'ZINES');
define('ABS_URL', DIRECTORY_SEPARATOR.ROOT_NAME.DIRECTORY_SEPARATOR);
define('ASSETS_DIR', 'assets'.DIRECTORY_SEPARATOR);
define('UPLOADS_DIR', ABS_URL.ASSETS_DIR.'medias'.DIRECTORY_SEPARATOR);
